export * from './desktop-onboarding-step-one/desktop-onboarding-step-one.component';
export * from './desktop-onboarding-step-two/desktop-onboarding-step-two.component';
export * from './desktop-house-rules-agreements/desktop-house-rules-agreements.component';
export * from './desktop-onboarding-step-four-startup/desktop-onboarding-step-four-startup.component';
export * from './desktop-onboarding-step-five-startup/desktop-onboarding-step-five-startup.component';
export * from './desktop-onboarding-step-three-startup/desktop-onboarding-step-three-startup.component';
export * from './desktop-onboarding-step-four-investor/desktop-onboarding-step-four-investor.component';
export * from './desktop-onboarding-step-five-investor/desktop-onboarding-step-five-investor.component';
export * from './desktop-onboarding-step-three-investor/desktop-onboarding-step-three-investor.component';
export * from './mobile-house-rules-agreements/mobile-house-rules-agreements.component';
export * from './mobile-onboarding-step-one/mobile-onboarding-step-one.component';
export * from './mobile-onboarding-step-two/mobile-onboarding-step-two.component';
export * from './mobile-onboarding-step-three/mobile-onboarding-step-three.component';
export * from './mobile-onboarding-step-four/mobile-onboarding-step-four.component';
export * from './mobile-onboarding-step-five-startup/mobile-onboarding-step-five-startup.component';
export * from './mobile-onboarding-step-six-startup/mobile-onboarding-step-six-startup.component';
export * from './mobile-onboarding-step-seven-startup/mobile-onboarding-step-seven-startup.component';
export * from './mobile-onboarding-step-eight-startup/mobile-onboarding-step-eight-startup.component';
export * from './mobile-onboarding-step-nine-startup/mobile-onboarding-step-nine-startup.component';
export * from './mobile-onboarding-step-five-investor/mobile-onboarding-step-five-investor.component';
export * from './mobile-onboarding-step-six-investor/mobile-onboarding-step-six-investor.component';
export * from './mobile-onboarding-step-seven-investor/mobile-onboarding-step-seven-investor.component';
export * from './mobile-onboarding-step-eight-investor/mobile-onboarding-step-eight-investor.component';
export * from './mobile-onboarding-step-nine-investor/mobile-onboarding-step-nine-investor.component';

export { defaultDesktopOnboardingStepTwoFormData } from './desktop-onboarding-step-two/desktop-onboarding-step-two.defaults';
export { defaultDesktopOnboardingStepOneFormData } from './desktop-onboarding-step-one/desktop-onboarding-step-one.defaults';
export { defaultDesktopOnboardingStepFourStartupFormData } from './desktop-onboarding-step-four-startup/desktop-onboarding-step-four-startup.defaults';
export { defaultDesktopOnboardingStepFiveStartupFormData } from './desktop-onboarding-step-five-startup/desktop-onboarding-step-five-startup.defaults';
export { defaultDesktopOnboardingStepFiveInvestorFormData } from './desktop-onboarding-step-five-investor/desktop-onboarding-step-five-investor.defaults';
export { defaultDesktopOnboardingStepThreeStartupFormData } from './desktop-onboarding-step-three-startup/desktop-onboarding-step-three-startup.defaults';
export { defaultDesktopOnboardingStepFourInvestorFormData } from './desktop-onboarding-step-four-investor/desktop-onboarding-step-four-investor.defaults';
export { defaultDesktopOnboardingStepThreeInvestorFormData } from './desktop-onboarding-step-three-investor/desktop-onboarding-step-three-investor.defaults';
export { defaultMobileOnboardingStepOneFormData } from './mobile-onboarding-step-one/mobile-onboarding-step-one.defaults';
export { defaultMobileOnboardingStepTwoFormData } from './mobile-onboarding-step-two/mobile-onboarding-step-two.defaults';
export { defaultMobileOnboardingStepThreeFormData } from './mobile-onboarding-step-three/mobile-onboarding-step-three.defaults';
export { defaultMobileOnboardingStepFourFormData } from './mobile-onboarding-step-four/mobile-onboarding-step-four.defaults';
export { defaultMobileOnboardingStepFiveStartupFormData } from './mobile-onboarding-step-five-startup/mobile-onboarding-step-five-startup.defaults';
export { defaultMobileOnboardingStepSixStartupFormData } from './mobile-onboarding-step-six-startup/mobile-onboarding-step-six-startup.defaults';
export { defaultMobileOnboardingStepSevenStartupFormData } from './mobile-onboarding-step-seven-startup/mobile-onboarding-step-seven-startup.defaults';
export { defaultMobileOnboardingStepEightStartupFormData } from './mobile-onboarding-step-eight-startup/mobile-onboarding-step-eight-startup.defaults';
export { defaultMobileOnboardingStepNineStartupFormData } from './mobile-onboarding-step-nine-startup/mobile-onboarding-step-nine-startup.defaults';
export { defaultMobileOnboardingStepFiveInvestorFormData } from './mobile-onboarding-step-five-investor/mobile-onboarding-step-five-investor.defaults';
export { defaultMobileOnboardingStepSixInvestorFormData } from './mobile-onboarding-step-six-investor/mobile-onboarding-step-six-investor.defaults';
export { defaultMobileOnboardingStepSevenInvestorFormData } from './mobile-onboarding-step-seven-investor/mobile-onboarding-step-seven-investor.defaults';
export { defaultMobileOnboardingStepEightInvestorFormData } from './mobile-onboarding-step-eight-investor/mobile-onboarding-step-eight-investor.defaults';
export { defaultMobileOnboardingStepNineInvestorFormData } from './mobile-onboarding-step-nine-investor/mobile-onboarding-step-nine-investor.defaults';
