export default {
  v: '5.7.14',
  fr: 60,
  ip: 0,
  op: 363,
  w: 1440,
  h: 1500,
  nm: '1_display_ HOME',
  ddd: 0,
  assets: [
    {
      id: 'image_0',
      w: 624,
      h: 724,
      p: '/images/match-mask.png',
      e: 0,
    },
    {
      id: 'image_1',
      w: 624,
      h: 724,
      p: '/images/match-card.png',
      e: 0,
    },
  ],
  fonts: {
    list: [
      {
        origin: 1,
        fPath: '',
        fClass: '',
        fFamily: 'Open Sans',
        fWeight: '',
        fStyle: 'SemiBold',
        fName: 'OpenSans-SemiBold',
        ascent: 76.009_450_683_370_2,
      },
      {
        origin: 1,
        fPath: '',
        fClass: '',
        fFamily: 'Open Sans',
        fWeight: '',
        fStyle: 'Medium',
        fName: 'Open Sans',
        ascent: 75.009_999_999_776_5,
      },
    ],
  },
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 3,
      nm: 'Null',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 0,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [-284, 750, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 10,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 14,
              s: [1349.5, 3454, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 136,
              s: [1349.5, 1111, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 11,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 12,
              s: [1349.5, 2667.5, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 134,
              s: [1349.5, 324.5, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 12,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 10,
              s: [1349.5, 1888, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 132,
              s: [1349.5, -455, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 13,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 8,
              s: [1349.5, 1110, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 130,
              s: [1349.5, -1233, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 14,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 6,
              s: [1349.5, 323.5, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 128,
              s: [1349.5, -2019.5, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 15,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 4,
              s: [1349.5, -456, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 126,
              s: [1349.5, -2799, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 16,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.125,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 24,
              s: [671.5, 3164.5, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 156,
              s: [671.5, 821.5, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 17,
      ty: 2,
      nm: 'main card3.png',
      cl: 'png',
      parent: 1,
      refId: 'image_1',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 22,
              s: [688, 2431, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 144,
              s: [688, 88, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [330, 400, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 18,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 20,
              s: [669.5, 1613, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 142,
              s: [669.5, -730, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 19,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 18,
              s: [671.5, 820.5, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 140,
              s: [671.5, -1522.5, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 20,
      ty: 2,
      nm: 'main card3.png',
      cl: 'png',
      parent: 1,
      refId: 'image_1',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 16,
              s: [688, 87, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 138,
              s: [688, -2256, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [330, 400, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 21,
      ty: 2,
      nm: 'card_filled.png',
      cl: 'png',
      parent: 1,
      refId: 'image_0',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.25,
                y: 1,
              },
              o: {
                x: 0.56,
                y: 0,
              },
              t: 14,
              s: [669.5, -731, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 136,
              s: [669.5, -3074, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [312, 362, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 363,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
