name: CI

on: [pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v4

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run prettier
        run: yarn format:check

      - name: Run typecheck
        run: yarn typecheck

      - name: Run lint
        run: yarn lint
