name: Renovate

on:
  schedule:
    - cron: "0 0 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
