name: Renovate

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.6.10
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
